version: '3.8'

services:
  db:
    container_name: api_database
    image: 'mysql:latest'
    environment: 
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
      - DATABASE_HOST=$DB_HOST
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    ports:
        - "3307:3306"
    volumes:
        - ./db/data:/lib/mysql
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    container_name: api
    build:
      context: .
      target: final
    ports:
      - "8000:8000"
    environment:
      - PORT=$PORT
      - SENDER_EMAIL=$SENDER_EMAIL
      - SENDER_EMAIL_PASSWORD=$SENDER_EMAIL_PASSWORD
      - SMTP_HOST=$SMTP_HOST
      - SMTP_PORT=$SMTP_PORT
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
    depends_on: 
      - db
    links:
      - db
    volumes:
      - .env:/app/.env
