version: '3.8'

services:
  server:
    container_name: api
    restart: on-failure
    build:
      context: .
      target: final
    ports:
      - "8000:8000"
    environment:
      - PORT=$PORT
      - SENDER_EMAIL=$SENDER_EMAIL
      - SENDER_EMAIL_PASSWORD=$SENDER_EMAIL_PASSWORD
      - SMTP_HOST=$SMTP_HOST
      - SMTP_PORT=$SMTP_PORT
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
    depends_on:
      - go_db
    volumes:
      - .env:/app/.env

  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:  
  pgdata: {}